kind: pipeline
name: default

steps:
## Lint Helm Charts
- name: helm-chart-tests
  image: quay.io/helmpack/chart-testing:v2.1.0
  commands:
    - ct lint --all --chart-dirs=deployment/helm --chart-repos=incubator=https://kubernetes-charts-incubator.storage.googleapis.com

## Run Unit tests
- name: unit-tests
  image: maven:3.6-jdk-11
  commands:
    - echo ugh
#    - mvn clean test -Dtest="*,!UserControllerTest,!UserServiceTests" -DfailIfNoTests=false

## build binaries to ensure they compile fine
- name: build-binaries
  image: maven:3.6-jdk-11
  commands:
    - mvn clean install -DskipTests -Ddockerfile.skip

## build and push docker image when master branch
- name: build-and-push-images
  when:
    branch:
    - master
  image: maven:3.6-jdk-11
  environment:
    DOCKER_USERNAME:
      from_secret: docker-username
    DOCKER_PASSWORD:
      from_secret: docker-password
  commands:
    - mvn compile jib:build -Ddocker.user=$${DOCKER_USERNAME}
