apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "edge-service.fullname" . }}
  labels:
    app: {{ include "edge-service.name" . }}
    chart: {{ include "edge-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "edge-service.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "edge-service.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "edge-service.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: RIBBON_EUREKA_ENABLED
              value: "false"
            - name: KUBERNETES_TRUST_CERT
              value: "true"
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
